print('Informe os seguintes números.')
dia = input('O dia que você nasceu?')
mes = input('O mês que você nasceu?')
ano = input('O ano que você nasceu?')
print('Você nasceu na data: ',dia,'/',mes,'/',ano,'. Correto?')