frase = 'Curso em Vídeo Python'
print(frase[:2])
print(frase[::2])
print(frase.count('o'))
print(len(frase))
print(frase.replace('Python', 'Android'))
print(frase.find('vídeo'))
print(frase.title())
dividido = frase.split()
print(dividido[0][3])
print('|~|'.join(dividido))
