n = input('Digite algo: ')
print('O que você digitou é do tipo {}'.format(type(n)))
print('O que você digitou é numérico: {}'.format(n.isnumeric()))
print('O que você digitou é decimal: {}'.format(n.isdecimal()))
print('O que você digitou é alfabético: {}'.format(n.isalpha()))
print('O que você digitou é alfanumérico: {}'.format(n.isalnum()))
print('O que você digitou está todo em maiuscula: {}'.format(n.isupper()))
print('O que você digitou está todo em minuscula: {}'.format(n.islower()))
print('O que você digitou é composto por espaços: {}'.format(n.isspace()))
print('O que você digitou está capitalizado: {}'.format(n.istitle()))
